#!/bin/python3

import math
import os
import random
import re
import sys

def even_odd(n):
    if n%2 != 0 or 6<=n<=20:
        print('Weird')
    else:
        if 2<n<5 or n > 20:
            print('Not Weird')

if __name__ == '__main__':
    n = int(input().strip())
    even_odd(n)
